import { GoogleGenAI } from "@google/genai";

// Initialize the client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Sends an image to Gemini to add a Christmas hat.
 * @param base64Image The base64 string of the user's uploaded image.
 * @param mimeType The mime type of the image (e.g., image/jpeg).
 * @returns The base64 string of the generated image.
 */
export const generateChristmasAvatar = async (
  base64Image: string,
  mimeType: string
): Promise<string> => {
  try {
    // We clean the base64 string if it contains the header
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // Optimized for image tasks
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType,
            },
          },
          {
            text: 'Add a cute red Christmas Santa hat to the head of the main subject in this image. The subject can be a person, a cartoon character, or an animal. Ensure the hat fits naturally on the head. Keep the face, expression, and background as close to the original as possible. Output a high-quality image.',
          },
        ],
      },
      // We do not set responseMimeType for image generation/editing tasks on this model
    });

    // Iterate through parts to find the image output
    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};